### ISSUE TITLE
chrome-extension unsupported breaking NativeMessagingHosts based plugins

### ISSUE THREAD

**Issue by Terramoto** [Decentr-net/decentr#93]
Hello,

While trying to setup the plugin KeepassXC on Decentr, the plugins communicates with the app running on the desktop to request and save the data. This communication is done via NativeMessagingHosts where the plugin sets the configuration for the app in a json file and adds the path to the registry:
`Computador\HKEY_CURRENT_USER\SOFTWARE\Chromium\NativeMessagingHosts\`

An example of the path content:
![image](https://user-images.githubusercontent.com/5443354/156340940-ff9e6489-1721-40cb-8e8c-9439f71b3d88.png)

(ignore the org.keepassxc.keepassxc_browser_decentr.json one this was my testing it)

An example of the configuration file would be:
```
{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoretcmckehcpafo/",
        "chrome-extension://oboonakemofpalerttoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "D:\\KeePassXC\\keepassxc-proxy.exe",
    "type": "stdio"
}
```

Decentr is able to go as far as finding the json files but then it doesn't accept it because it's looking for the chromium.json file, this one contains chrome-extension:// scheme which is not supported by Decentr. I tried creating the decentr.json containing the decentr-extension:// scheme but the browser goes directly for chromium.json. Upon changing the scheme in chromium.json the addon works well.

I'm guessing a solution would be for Decentr look for is own json file ending in decentr.json and add support for chrome-extension:// scheme for the sake of supporting other plugins using this type of communication. In Brave the file used ends in brave.json but the scheme is still "chrome-extension://".

**Comment by sunzxs** [comment]
Hello, @Terramoto!

We've changed `decentr-extension://` to `chrome-extension://` in the last browser release (v1.1.6).
You may download the actual version of Decentr Browser from [https://decentr.net](https://decentr.net/#download).

Please could you try to install KeepassXC on Decentr Browser v1.1.6 and put your feedback in the thread?

**Comment by Terramoto** [comment]
Hello,

This has been tested and it seems to be working now.
